#!/usr/bin/env bash

export CONTECO_LABEL="nginx.rewrite - ContEco"
export CONTECO_DESCRIPTION="Nginx Rewrite implements a generic URL rewrite template using environment variables."

export CONTECO_TYPE="nginx"
export CONTECO_NAME="rewrite"
export CONTECO_TAG="1.17.3"

export CONTECO_BASE="nginx.base:1.17.3"
export CONTECO_BUILD="image"
