---
version: '3'
services:

# START SERVICE nginx.rewrite
  nginx:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM}/${CONTECO_ECOSYSTEM}.nginx.rewrite:v1.0.0
    environment: ['CONTECO_NGINX_CONF_LOCATION=${CONTECO_DC_NGINX_REWRITE_ENVIRONMENT_CONF_PATH}', 'CONTECO_NGINX_CONF_PROXY_PASS=${CONTECO_DC_NGINX_REWRITE_ENVIRONMENT_CONF_UPSTREAM}']
    command: []
    volumes: []
    ports: [${CONTECO_DC_NGINX_REWRITE_PORTS}]
    networks: [${CONTECO_DC_NGINX_REWRITE_NETWORKS}]
    deploy:
      mode: replicated
      resources:
        limits:
          cpus: '${CONTECO_DC_NGINX_REWRITE_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${CONTECO_DC_NGINX_REWRITE_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${CONTECO_DC_NGINX_REWRITE_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${CONTECO_DC_NGINX_REWRITE_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      labels: [${CONTECO_DC_NGINX_REWRITE_DEPLOY_LABELS}]
# END SERVICE nginx.rewrite

volumes: {${CONTECO_DC_GLOBAL_VOLUMES}}
networks: {${CONTECO_DC_GLOBAL_NETWORKS}}
